# Generated by Django 6.0.1 on 2026-01-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='campus',
            field=models.CharField(choices=[('P', 'Peshawar'), ('F', 'Faisalabad'), ('L', 'Lahore'), ('I', 'Islamabad'), ('K', 'Karachi'), ('M', 'Multan')], default='P', max_length=1),
        ),
    ]
