# Generated by Django 6.0.1 on 2026-01-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_blood_group_alter_user_cnic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
