# Generated by Django 6.0.1 on 2026-01-18 03:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_student_degree_alter_student_program_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cnic',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{7}-\\d{1}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{7}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]*$')]),
        ),
    ]
