# Generated by Django 6.0.1 on 2026-01-18 03:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_cnic_alter_user_mobile_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9]{2}[A-Z]-[0-9]{4}$')]),
        ),
    ]
