# Generated by Django 6.0.1 on 2026-01-18 03:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{7}$')]),
        ),
    ]
