# Generated by Django 6.0.1 on 2026-01-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_user_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authentication',
            old_name='hash_password',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='academicrequest',
            name='request_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='authentication',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.IntegerField(max_length=4),
        ),
    ]
