# Generated by Django 6.0.1 on 2026-01-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_hash_password_authentication_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterField(
            model_name='authentication',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
