# Generated by Django 6.0.1 on 2026-01-21 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_address_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[0-9]{4}$')]),
        ),
    ]
